; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "PhoXoSee"
#define MyAppVersion "1.9.26.3"
#define MyAppPublisher "FULI"
#define MyAppExeName "PhoXoSee.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{405A2551-1951-4DAE-8902-93FCBEB115EF}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppCopyright=Copyright (C) 2026 FULI
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
DefaultGroupName={#MyAppName}
DisableReadyPage=yes

;DisableFinishedPage=no
;DisableWelcomePage=no
OutputDir=.\bin\
OutputBaseFilename=phoxosee_{#MyAppVersion}
SolidCompression=yes
;UsePreviousAppDir=yes
SetupIconFile=..\..\PhoXoSee\res\PhoXoSee.ico
WizardStyle=modern
UninstallDisplayName={#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
VersionInfoVersion={#MyAppVersion}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
WizardImageFile=WizardImageFile.png,WizardImageFile2.png,WizardImageFile3.png,WizardImageFile4.png,WizardImageFile5.png
;WizardSmallImageFile=WizardSmallImageFile.bmp
ShowLanguageDialog=auto
MinVersion=10.0
CloseApplications=force
;PrivilegesRequired=admin

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
;Name: "chinesesimplified"; MessagesFile: "compiler:Languages\ChineseSimplified.isl"
;Name: "chinesetraditional"; MessagesFile: "compiler:Languages\ChineseTraditional.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "korean"; MessagesFile: "compiler:Languages\Korean.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"
;Name: "vietnam"; MessagesFile: "compiler:Languages\Vietnamese.isl"
Name: "ukraine"; MessagesFile: "compiler:Languages\Ukrainian.isl"
Name: "Polish"; MessagesFile: "compiler:Languages\Polish.isl"

[Files]
Source: "..\bin\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
;Source: "..\bin\PhoXoSee.exe"; DestDir: "{app}"; Flags: ignoreversion
;Source: "..\bin\image.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "..\bin\ShellMenu.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "..\bin\language\*"; DestDir: "{app}\language"; Flags: ignoreversion recursesubdirs createallsubdirs
;Source: "..\bin\res\*"; DestDir: "{app}\res"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
;Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"

[Run]
Filename: "{app}\{#MyAppExeName}"; Parameters: "/install"; Flags: waituntilterminated
Filename: "{app}\{#MyAppExeName}"; Flags: nowait postinstall skipifsilent

[UninstallRun]
Filename: "{app}\{#MyAppExeName}"; Parameters: "/uninstall"; RunOnceId: "phoxoseeuninstall"

;--------------------------------
; Code (替代 NSIS System::Call DLL)
[Code]
procedure RunBeforeInstall();
external 'RunBeforeInstall@files:SetupHelper.dll stdcall';

function InitializeSetup(): Boolean;
begin
  ExtractTemporaryFile('SetupHelper.dll');

  try
    RunBeforeInstall();
  except
    MsgBox('SetupHelper.dll call failed.', mbError, MB_OK);
  end;

  Result := True;
end;
